spring:
  jpa:
    database: MYSQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: mysql
    url: jdbc:mysql://host.docker.internal:3306/deposit_service_database?useSSL=false
    username: bestuser
    password: bestuser
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    port: 5672
    host: rabbitmq
    username: guest
    password: guest
    listener:
      direct:
        default-requeue-rejected: true

server:
  port: 9999